FROM python:3.9-slim

WORKDIR /app

COPY bot.py /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y ffmpeg && apt-get clean

CMD ["python", "bot.py"]